name: HeavenCore
version: 3.0
main: fr.hc.core.BukkitHeavenCore
depend: [WorldEdit]
commands:
 creacheat:
  usage: /creacheat
  description: Active/désactive le Gamemode 1.
 endercheat:
  usage: /endercheat <joueur>
  description: Ouvre l'endercheat du joueur concerné.
 heal:
  usage: /heal [<joueur>]
  description: Soigne le joueur.
 inventory:
  usage: /inventory <joueur>
  description: Ouvre l'inventaire du joueur.
 roucoups:
  usage: /roucoups
  description: Donne le fly au joueur.
 spectator:
  usage: /spectator
  description: Active/Désactive le Gamemode 3.
 home:
  usage: /home <nombre>
  description: Téléporte à un home.
 sethome:
  usage: /sethome <id>
  description: Définie la position d'un home.
 buyhome:
  usage: /buyhome
  description: Achète un home en plus.
 tphome:
  usage: /tphome <joueur> <numéro>
  description: Permet de se téléporter au home d'un joueur.
 cheval:
  usage: /cheval
  description: Gère la propriété d'un cheval.
 tp:
  usage: /tp <joueur>
  description: Téléporte à un joueur.
 tphere:
  usage: /tphere <joueur>
  description: Téléporte un joueur à soi.
 tppos:
  usage: /tppos <x> <y> <z>
  description: Téléporte à des coordonnées.
 poof:
  usage: /poof
  description: Rend l'utilisateur invisible.