name: HeavenRP
version: 3.0
main: fr.hc.rp.BukkitHeavenRP
depend: [HeavenCore]
commands:
 test:
   description: Commande pour tester de nouvelles fonctionalités.
   usage: /test
 spawn:
   description: Téléporte au spawn.
   usage: /spawn
 warp:
   description: Téléporte a un endroit donné.
   usage: /warp
 bourse:
   description: Informe du solde du porte-monnaie
   usage: /bourse
 parcelle:
   description: Permet aux maires de gérer leurs parcelles
   usage: /parcelle
 payer:
   description: Permet de payer un joueur, une ville ou une entreprise.
   usage: /payer <ville/joueur/entreprise> <nom> <montant>
 ville:
   description: Afficher les informations d'une ville
   usage: /ville
 rejoindre:
   description: Rejoindre un joueur
   usage: /rejoindre <joueur>
 accepter:
   description: Accepter la téléportation d'un joueur
   usage: /accepter <joueur>
 entreprise:
   description: Gérer son entreprise
   usage: /entreprise
