name: HeavenRP
version: 3.0
main: fr.hc.rp.BukkitHeavenRP
depend: [HeavenCore]
commands:
 spawn:
   description: Téléporte au spawn.
   usage: /spawn
 warp:
   description: Téléporte a un endroit donné.
   usage: /warp
 bourse:
   description: Informe du solde du porte-monnaie
   usage: /bourse
    